name: Courses Periodic Update

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install Intermediate Certificates
        run: |
          openssl s_client -showcerts -servername students.technion.ac.il -connect students.technion.ac.il:443 | sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' > ~/technion.crt
          sudo mv ~/technion.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates
      - name: Run Periodic Update
        run: bash deploy.sh
        env:
          MOODLE_SESSIONSTUDENTSPROD: ${{ secrets.MOODLE_SESSIONSTUDENTSPROD }}
          COURSE_INFO_FETCHER_PROXY: ${{ secrets.COURSE_INFO_FETCHER_PROXY }}
          COURSE_INFO_FETCHER_PROXY_URL: ${{ secrets.COURSE_INFO_FETCHER_PROXY_URL }}
          COURSE_INFO_FETCHER_PROXY_AUTH: ${{ secrets.COURSE_INFO_FETCHER_PROXY_AUTH }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
